### PR TITLE
add 242. Valid Anagram

### PR DESCRIPTION
**Pull request by kobakobashu**
time : 15m

### CODE REVIEW

**Comment by kobakobashu** [comment]
Please check my code

**Review by ryuji0123 — CHANGES_REQUESTED** [review]
use collections.Counter and solve this with O(n) time complexity

**Comment by kobakobashu** [comment]
I used collections.Counter and solved this with O(n) time complexity.  Please check my code.

**Review by ryuji0123 — CHANGES_REQUESTED** [review]
See 448

**Comment by kobakobashu** [comment]
I modified my code.  Please check it.

**Review by tkkawa — APPROVED** [review]
LGTM

**Pull request closed without merging**
